### ISSUE TITLE
Hack Prozess pro node

### ISSUE THREAD

**Issue by Forcasius** [UnfinishedGames/MatrixRunner2054#1]
Jede Node braucht ihren eigenen Hack Prozess

**Comment by GitInMaRepo** [comment]
Würde ich auf später (Sobald es Spielmodi gibt) verschieben

**Comment by Forcasius** [comment]
Jede Node kann jetzt ein Child haben, welches ein Hacking script enthält. Dieses steuert welches Minigame gestartet wird, wenn der Hackprozess eingeleitet wird. Dadurch hat sich die Verantwortung des Status in die neue Scene verschoben.
