### ISSUE TITLE
Spieler auf Spawnpunkt der AI 

### ISSUE THREAD

**Issue by GitInMaRepo** [UnfinishedGames/MatrixRunner2054#10]
Wenn der Spieler auf den Spawnpunkt der AI kommt, befinden wir uns in einer Endlosschleife.

**Comment by Forcasius** [comment]
fixed with commit 3f8847103bbf5150d3f87d0b5aa5303cdca3d28d

Das ICE wird auf den Spielerstartpunkt gesetzt, wenn der Spieler den Startpunkt vom ICE belegt
