### ISSUE TITLE
Ein Missionmanager wird benötigt

### ISSUE THREAD

**Issue by Forcasius** [UnfinishedGames/MatrixRunner2054#7]
Der hällt alle Infos, die für die aktuelle Mission wichtig sind
(Wie sieht ein Kampf aus, welches ICE gibt es, wie lange Dauert ein Hack,...))

**Comment by GitInMaRepo** [comment]
Das grobe Gerüst für Missionsmanagement steht:

- Der Missionsmanager lässt sich eine Mission von der Strategy geben und initialisiert die Mission. 
- Ein standardisiertes Interface gibt Modulen die Möglichkeit, einer Mission Informationen zu geben.
- Eine Mission kann nach ihrem Zustand abgefragt werden
